/**
 * 시그널 서버 API
 * 소프트웨어 마에스트로 과정
 * <p>
 * OpenAPI spec version: 0.0.1
 * <p>
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 * <p>
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * <p>
 * http://www.apache.org/licenses/LICENSE-2.0
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model;

import io.swagger.annotations.*;

import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class InlineResponse2013 {

    @SerializedName("id")
    private Integer id = null;
    @SerializedName("title")
    private String title = null;
    @SerializedName("introduce")
    private String introduce = null;
    @SerializedName("is_enabled")
    private Boolean isEnabled = null;
    @SerializedName("publisher")
    private Object publisher = null;
    @SerializedName("signaler")
    private Object signaler = null;

    /**
     **/
    @ApiModelProperty(value = "")
    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public String getIntroduce() {
        return introduce;
    }

    public void setIntroduce(String introduce) {
        this.introduce = introduce;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public Boolean getIsEnabled() {
        return isEnabled;
    }

    public void setIsEnabled(Boolean isEnabled) {
        this.isEnabled = isEnabled;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public Object getPublisher() {
        return publisher;
    }

    public void setPublisher(Object publisher) {
        this.publisher = publisher;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public Object getSignaler() {
        return signaler;
    }

    public void setSignaler(Object signaler) {
        this.signaler = signaler;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        InlineResponse2013 inlineResponse2013 = (InlineResponse2013) o;
        return (this.id == null ? inlineResponse2013.id == null : this.id.equals(inlineResponse2013.id)) &&
                (this.title == null ? inlineResponse2013.title == null : this.title.equals(inlineResponse2013.title)) &&
                (this.introduce == null ? inlineResponse2013.introduce == null : this.introduce.equals(inlineResponse2013.introduce)) &&
                (this.isEnabled == null ? inlineResponse2013.isEnabled == null : this.isEnabled.equals(inlineResponse2013.isEnabled)) &&
                (this.publisher == null ? inlineResponse2013.publisher == null : this.publisher.equals(inlineResponse2013.publisher)) &&
                (this.signaler == null ? inlineResponse2013.signaler == null : this.signaler.equals(inlineResponse2013.signaler));
    }

    @Override
    public int hashCode() {
        int result = 17;
        result = 31 * result + (this.id == null ? 0 : this.id.hashCode());
        result = 31 * result + (this.title == null ? 0 : this.title.hashCode());
        result = 31 * result + (this.introduce == null ? 0 : this.introduce.hashCode());
        result = 31 * result + (this.isEnabled == null ? 0 : this.isEnabled.hashCode());
        result = 31 * result + (this.publisher == null ? 0 : this.publisher.hashCode());
        result = 31 * result + (this.signaler == null ? 0 : this.signaler.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class InlineResponse2013 {\n");

        sb.append("  id: ").append(id).append("\n");
        sb.append("  title: ").append(title).append("\n");
        sb.append("  introduce: ").append(introduce).append("\n");
        sb.append("  isEnabled: ").append(isEnabled).append("\n");
        sb.append("  publisher: ").append(publisher).append("\n");
        sb.append("  signaler: ").append(signaler).append("\n");
        sb.append("}\n");
        return sb.toString();
    }
}
