/**
 * 시그널 서버 API
 * 소프트웨어 마에스트로 과정
 * <p>
 * OpenAPI spec version: 0.0.1
 * <p>
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 * <p>
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * <p>
 * http://www.apache.org/licenses/LICENSE-2.0
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model;

import io.swagger.annotations.*;

import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class InlineResponse2012 {

    @SerializedName("id")
    private String id = null;
    @SerializedName("short_opinion")
    private String shortOpinion = null;
    @SerializedName("meeting")
    private Object meeting = null;
    @SerializedName("signaler")
    private Object signaler = null;

    /**
     **/
    @ApiModelProperty(value = "")
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public String getShortOpinion() {
        return shortOpinion;
    }

    public void setShortOpinion(String shortOpinion) {
        this.shortOpinion = shortOpinion;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public Object getMeeting() {
        return meeting;
    }

    public void setMeeting(Object meeting) {
        this.meeting = meeting;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public Object getSignaler() {
        return signaler;
    }

    public void setSignaler(Object signaler) {
        this.signaler = signaler;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        InlineResponse2012 inlineResponse2012 = (InlineResponse2012) o;
        return (this.id == null ? inlineResponse2012.id == null : this.id.equals(inlineResponse2012.id)) &&
                (this.shortOpinion == null ? inlineResponse2012.shortOpinion == null : this.shortOpinion.equals(inlineResponse2012.shortOpinion)) &&
                (this.meeting == null ? inlineResponse2012.meeting == null : this.meeting.equals(inlineResponse2012.meeting)) &&
                (this.signaler == null ? inlineResponse2012.signaler == null : this.signaler.equals(inlineResponse2012.signaler));
    }

    @Override
    public int hashCode() {
        int result = 17;
        result = 31 * result + (this.id == null ? 0 : this.id.hashCode());
        result = 31 * result + (this.shortOpinion == null ? 0 : this.shortOpinion.hashCode());
        result = 31 * result + (this.meeting == null ? 0 : this.meeting.hashCode());
        result = 31 * result + (this.signaler == null ? 0 : this.signaler.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class InlineResponse2012 {\n");

        sb.append("  id: ").append(id).append("\n");
        sb.append("  shortOpinion: ").append(shortOpinion).append("\n");
        sb.append("  meeting: ").append(meeting).append("\n");
        sb.append("  signaler: ").append(signaler).append("\n");
        sb.append("}\n");
        return sb.toString();
    }
}
